config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :stories, only: [:create, :destroy]
  end
  resources :stories
  root to: 'stories#index'
  get 'users/sign_up', to: "users#new"
  post 'users', to: "users#create"
  get 'users/sign_in', to: "sessions#new"
  resources :sessions, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/historia.rb
class Historia < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def authenticate_user!
    redirect_to users_sign_in_path unless helpers.logged?
  end
end

app/controllers/historia_controller.rb
class HistoriaController < ApplicationController
  before_action :set_historium, only: [:show, :edit, :update, :destroy]

  # GET /historia
  # GET /historia.json
  def index
    @historia = Historium.all
  end

  # GET /historia/1
  # GET /historia/1.json
  def show
  end

  # GET /historia/new
  def new
    @historium = Historium.new
  end

  # GET /historia/1/edit
  def edit
  end

  # POST /historia
  # POST /historia.json
  def create
    @historium = Historium.new(historium_params)

    respond_to do |format|
      if @historium.save
        format.html { redirect_to @historium, notice: 'Historium was successfully created.' }
        format.json { render :show, status: :created, location: @historium }
      else
        format.html { render :new }
        format.json { render json: @historium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historia/1
  # PATCH/PUT /historia/1.json
  def update
    respond_to do |format|
      if @historium.update(historium_params)
        format.html { redirect_to @historium, notice: 'Historium was successfully updated.' }
        format.json { render :show, status: :ok, location: @historium }
      else
        format.html { render :edit }
        format.json { render json: @historium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historia/1
  # DELETE /historia/1.json
  def destroy
    @historium.destroy
    respond_to do |format|
      format.html { redirect_to historia_url, notice: 'Historium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historium
      @historium = Historium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historium_params
      params.require(:historium).permit(:titulo, :narracion)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
  reset_session
  redirect_to users_sign_up_path
end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user.nil?
      redirect_to users_sign_in_path, alert: 'El usuario no existe'
      return
    end

    if @user.password == params[:user][:password]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to users_sign_in_path, alert: 'El p'
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = helpers.current_user
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:titulo, :narracion)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end


  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/historia_helper.rb
module HistoriaHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged?
    session[:user_id].present? ? true : false
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/views/historia/_form.html.erb
<%= form_with(model: historium, local: true) do |form| %>
  <% if historium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historium.errors.count, "error") %> prohibited this historium from being saved:</h2>

      <ul>
      <% historium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :narracion %>
    <%= form.text_field :narracion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/historia/edit.html.erb
<h1>Editing Historium</h1>

<%= render 'form', historium: @historium %>

<%= link_to 'Show', @historium %> |
<%= link_to 'Back', historia_path %>

app/views/historia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historia</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Narracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historia.each do |historium| %>
      <tr>
        <td><%= historium.titulo %></td>
        <td><%= historium.narracion %></td>
        <td><%= link_to 'Show', historium %></td>
        <td><%= link_to 'Edit', edit_historium_path(historium) %></td>
        <td><%= link_to 'Destroy', historium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historium', new_historium_path %>

app/views/historia/new.html.erb
<h1>New Historium</h1>

<%= render 'form', historium: @historium %>

<%= link_to 'Back', historia_path %>

app/views/historia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @historium.titulo %>
</p>

<p>
  <strong>Narracion:</strong>
  <%= @historium.narracion %>
</p>

<%= link_to 'Edit', edit_historium_path(@historium) %> |
<%= link_to 'Back', historia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= alert %>
    <%= notice %>
    <% if logged? %>
        Bienvenido <%= current_user.email %>
        <%= link_to "Salir", session_path(current_user), method: :delete %>
    <% else %>
      El usuario no ha ingresado
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :narracion %>
    <%= form.text_field :narracion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Titulo</th>
      <th>Narracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.user_id %></td>
        <td><%= story.titulo %></td>
        <td><%= story.narracion %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @story.titulo %>
</p>

<p>
  <strong>Narracion:</strong>
  <%= @story.narracion %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/users/new.html.erb
<h1>CREAR NUEVO USUARIO </h1>
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories by <td></td></h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Narracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.stories.each do |story| %>
      <tr>
        <td><%= story.titulo %></td>
        <td><%= story.narracion %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>